--CREATING SILVER LAYER erp_cust_az12

INSERT INTO silver.erp_cust_az12(
	cid,
	bdate,
	gen)
SELECT
CASE WHEN cid LIKE 'NAS%' THEN SUBSTRING(cid,4,LEN(cid))
	ELSE cid
END AS cid,	--REMOVE 'NAS' PREFIX IF PRESENT
CASE WHEN bdate>GETDATE() THEN NULL
	ELSE bdate
END AS bdate,	--SET FUTURE BIRTHDATES TO NULL
CASE WHEN UPPER(TRIM(gen)) IN ('F','Female') THEN 'FEMALE'
	 WHEN UPPER(TRIM(gen)) IN ('M','Male') THEN 'MALE'
	 ELSE 'N/A'
END AS gen	--NORMALIZE GENDER VALUES & HANDLE UNKNOWN CASES
FROM bronze.erp_cust_az12;